[[sources]]
name = "Hacker News"
url = "https://news.ycombinator.com/rss"
type = "rss"
tags = ["tech", "programming", "startups"]
trust_level = 0.8

[[sources]]
name = "Ars Technica"
url = "https://feeds.arstechnica.com/arstechnica/index"
type = "rss"
tags = ["tech", "science", "policy"]
trust_level = 0.8

[[sources]]
name = "The Verge"
url = "https://www.theverge.com/rss/index.xml"
type = "rss"
tags = ["tech", "culture", "gadgets"]
trust_level = 0.7

[[sources]]
name = "New York Times"
url = "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml"
type = "rss"
tags = ["news", "politics", "events"]
trust_level = 0.7

[[sources]]
name = "MarketWatch"
url = "http://feeds.marketwatch.com/marketwatch/topstories"
type = "rss"
tags = ["finances", "money", "stocks"]
trust_level = 0.5

[[sources]]
name = "The Points Guy"
url = "https://thepointsguy.com/feed/"
type = "rss"
tags = ["travel", "money", "ads"]
trust_level = 0.3

[[sources]]
name = "EFF Deeplinks"
url = "https://www.eff.org/rss/updates.xml"
type = "rss"
tags = ["tech", "privacy", "politics"]
trust_level = 0.8

[[sources]]
name = "Rock Paper Shotgun"
url = "https://www.rockpapershotgun.com/feed/reviews"
type = "rss"
tags = ["gaming", "entertainment", "art"]
trust_level = 0.5

[[sources]]
name = "Damn That’s Interesting"
url = "https://www.damninteresting.com/feed/"
type = "rss"
tags = ["trivia", "funny", "history"]
trust_level = 0.5

[[sources]]
name = "CommonwealthBeacon"
url = "https://commonwealthbeacon.org/feed/"
type = "rss"
tags = ["politics", "local", "news"]
trust_level = 1.0

[[sources]]
name = "Tedium"
url = "https://tedium.co/rss/"
type = "rss"
tags = ["trivia", "history", "culture"]
trust_level = 0.5

[[sources]]
name = "Futility Closet"
url = "https://www.futilitycloset.com/feed/"
type = "rss"
tags = ["puzzles", "funny", "trivia"]
trust_level = 0.6

[[sources]]
name = "XKCD"
url = "https://xkcd.com/rss.xml"
type = "rss"
tags = ["humor", "tech", "comic"]
trust_level = 0.8
